apiVersion: v1
kind: PersistentVolume
metadata:
  name: museumdb-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: museumdb-mssql-persistent
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: museumdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
